### ISSUE TITLE
Adopt standard testing rules

### ISSUE THREAD

**Issue by pp-mo** [SciTools-incubator/iris-ugrid#17]
We'll want a "standard arrangement" structure + some rules, to organise our tests.

Can be analagous to [the Iris ones](https://scitools.org.uk/iris/docs/latest/developers_guide/tests.html#).
In-particular // at-least : 
  * tests for all public API components
  * unit-tests organised into standard structures by class/method.function, matching the package hiearchy
    * **but** not really clear how this will look when using pytest instead of unittest ?

In addition/alternative to Iris practices, I suggest :
  * use pytest to best advantage (or, work out how to).
  * minimise use of Mock, or any implementation-dependent testing
  * minimise use of 'rubber-stamp' testing like comparing `str` or `repr` forms, or `iris.tests.assertCML()`
    * i.e. where possible, test of relevant (public) properties instead of a 'total content dump' approach.
  * consider division into standard-ci and extended testing (maybe targetted by some future overnight testing strategy?)

----
TODOs
 - [ ] add a guide document for testing 'rules' in iris-ugrid
 - [ ] ensure all existing tests conform
 - [ ] add check to the definition-of-done 
    * ( I would also say, write a runnable test to check this, but I don't think this stuff is machine-enforceable ! )

**Comment by trexfeathers** [comment]
This repo has been superseded - loading UGRID is now incorporated into [SciTools/iris](https://github.com/SciTools/iris), and the regridding has migrated to [SciTools-incubator/iris-esmf-regrid](https://github.com/SciTools-incubator/iris-esmf-regrid).
