### ISSUE TITLE
Implement code coverage testing

### ISSUE THREAD

**Issue by pp-mo** [SciTools-incubator/iris-ugrid#18]
With a hook in the repo for testing on a PR.
Implement via pytest.
See e.g. https://github.com/SciTools/tephi

**Comment by trexfeathers** [comment]
Latest suggestion seems to be codecov - see SciTools-incubator/iris-esmf-regrid#9

**Comment by trexfeathers** [comment]
This repo has been superseded - loading UGRID is now incorporated into [SciTools/iris](https://github.com/SciTools/iris), and the regridding has migrated to [SciTools-incubator/iris-esmf-regrid](https://github.com/SciTools-incubator/iris-esmf-regrid).
