### ISSUE TITLE
Tidy API of regrid (?)

### ISSUE THREAD

**Issue by pp-mo** [SciTools-incubator/iris-ugrid#19]
Some retrospective ideas following #10 
Probably not worth pursuing now  : until this progresses to be a stable, supported public API (which might never happen).

All possible, to be considered/investigated :
 * [ ] ? add a `crs` option to the `regrid.MeshInfo()` constructor, to match `regrid.GridInfo`
 * [ ] ? rename the `regrid.GridInfo()` args 'lats', 'lons' etc to 'x'/ 'y', to suit the generality of the `crs` usage
 * [ ] ? make `MeshInfo.size` and `GridInfo.size` private, as purpose to the user is not really clear
    * (***or***) just document them fully

**Comment by trexfeathers** [comment]
This repo has been superseded - loading UGRID is now incorporated into [SciTools/iris](https://github.com/SciTools/iris), and the regridding has migrated to [SciTools-incubator/iris-esmf-regrid](https://github.com/SciTools-incubator/iris-esmf-regrid).
