### ISSUE TITLE
Additional unit-testing for `iris-ugrid.regrid`

### ISSUE THREAD

**Issue by pp-mo** [SciTools-incubator/iris-ugrid#20]
Like #19 , this may not be needed yet.
However, unlike that, this will be needed at *some* point, if the regrid code becomes part of a stable release.

Basically, bring testing into line with a #17.
At present, we are lacking some specific aspects ..
  * tests for additional, optional args in `MeshInfo().__init__` :
    * `node_start_index`, `elem_start_index`, `areas`
    * testing for mathematical results is not necessary : that would be testing ESMF rather than iris-ugrid
    * ( ... should test the resulting object properties instead )
  * tests for additional, optional args in `GridInfo().__init__` :
    * for `crs`, actual behaviour/results testing is needed
    * for `circular` / `areas`, previous note applies : just check properties of created object
  * `Regridder.regrid` needs test for `mdtol` argument.
    * needs to check actual functional correctness

**Comment by trexfeathers** [comment]
This repo has been superseded - loading UGRID is now incorporated into [SciTools/iris](https://github.com/SciTools/iris), and the regridding has migrated to [SciTools-incubator/iris-esmf-regrid](https://github.com/SciTools-incubator/iris-esmf-regrid).
