### ISSUE TITLE
Handle source masking in the `regrid()` call

### ISSUE THREAD

**Issue by pp-mo** [SciTools-incubator/iris-ugrid#21]
As noted [in the code comments](https://github.com/SciTools-incubator/iris-ugrid/blob/0.1.0regrid1/iris_ugrid/regrid.py#L419), the use of the `mdtol` argument is slightly misleading :
It only labels output cells as missing where there is insufficient overlap with the boundary of the source grid,
  \- it does ***not*** support masked source points.

This can definitely be done, but maybe at a computational cost.
There is a crude implementation in Iris [here](https://github.com/SciTools/iris/blob/v2.4.0/lib/iris/analysis/_regrid.py#L292).

**Comment by trexfeathers** [comment]
This repo has been superseded - loading UGRID is now incorporated into [SciTools/iris](https://github.com/SciTools/iris), and the regridding has migrated to [SciTools-incubator/iris-esmf-regrid](https://github.com/SciTools-incubator/iris-esmf-regrid).
