### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by bjlittle** [SciTools-incubator/iris-ugrid#22]
The `iris-ugrid` is missing its `LICENSE` file.

I think this is a general oversight, but I'd vote for this repo to be [BSD-3 Clause](https://opensource.org/licenses/BSD-3-Clause), rather than `LGPL`. 

Note that, we are in the process of moving `iris` away from `LGPL` to `BSD-3 Clause`.

This would invalidate any source code preamble headers.

**Comment by trexfeathers** [comment]
Closing since this is more appropriate as as comment on #1.
