### ISSUE TITLE
PEP440 compliance

### ISSUE THREAD

**Issue by bjlittle** [SciTools-incubator/iris-ugrid#34]
Suggest that [PEP440](https://www.python.org/dev/peps/pep-0440/) versioning is used.

**Comment by trexfeathers** [comment]
This has now become a blocker to benchmarking using [Airspeed Velocity](https://asv.readthedocs.io/en/stable/index.html), owing to the [default install command](https://asv.readthedocs.io/en/stable/asv.conf.json.html#build-command-install-command-uninstall-command):

```
in-dir={env_dir} python -mpip install {wheel_file}
```

[pip v21.0](https://github.com/pypa/pip/releases/tag/21.0) now mandates [PEP440](https://www.python.org/dev/peps/pep-0440/) within wheels (pypa/pip#9320).
