### ISSUE TITLE
Add requirements text file(s)

### ISSUE THREAD

**Issue by trexfeathers** [SciTools-incubator/iris-ugrid#6]
Base on other SciTools repos ([tephi](https://github.com/SciTools/tephi) as usual being the flagship example).

Known requirements introduced by #4:

- run
  - iris
  - gridded
- test
  - iris-test-data

Not sure how to reconcile the fact that we need special commit hashes for iris and iris-test-data (see #7 for details). I notice Iris doesn't actually mention iris-test-data in its [test requirements](https://github.com/SciTools/iris/blob/master/requirements/test.txt).

**Comment by pp-mo** [comment]
I think this is probably addressed (minimally) by #11.
As we require specific commits from both iris and iris-test-data, not releases, I think it makes sense to leave those out of the requirements files, if these are only used by Travis.
If they have other, more public, purposes, perhaps we need to address that : At present, we would have to specify Iris >= 3.0, which will help no-one much ! 😉
